### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by pmprog** [bzar/funkeymonkey#2]
On Intel NUC running Linux Mint 17. Any ideas?

```
~ > ./funkeymonkey -h
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
```

GDB output

```
(gdb) run
Starting program: /home/username/funkeymonkey/build/funkeymonkey 
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

Program received signal SIGABRT, Aborted.
0x00007ffff732dcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by bzar** [comment]
Not immediately. In my code the -h is handled before any regex handling is done, so it should not be there. I'll see if I can reproduce this somehow.

**Comment by pmprog** [comment]
If there's anything you need me to provide, let me know

**Comment by bzar** [comment]
I'm not able to reproduce that crash. Could you get me the full gdb stack trace and the version numbers of your compiler and libstdc++?

**Comment by pmprog** [comment]
gcc 4.8
cmake 2.8.12.2

---

~/code/funkeymonkey/build > /sbin/ldconfig -p | grep stdc++
        libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.6
        libstdc++.so.5 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.5

~/code/funkeymonkey/build > strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

~/code/funkeymonkey/build > ls -l /usr/lib/x86_64-linux-gnu/libstdc++.so.6
lrwxrwxrwx 1 root root 19 May 14 19:11 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.19

---

(gdb) bt full
#0  0x00007ffff732dcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 3207
        selftid = 3207
#1  0x00007ffff73310d8 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {6474496, 6476856, 140737351947607, 140733193388033, 0, 140737344399464, 140737340497192, 
              140737344399464, 6476856, 6476880, 140737351976213, 140737353873248, 140737341433968, 1, 140737353875600, 6476592}}, sa_flags = 10, sa_restorer = 0x7ffff7fbf780}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7932535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff79306d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff7930703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff7930922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7982935 in std::__throw_regex_error(std::regex_constants::error_type) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x000000000042152e in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression (this=this@entry=0x7fffffffda60)
    at /usr/include/c++/4.8/bits/regex_compiler.h:974
        __matcher = {_M_traits = @0x62cb08, _M_is_non_matching = false}
#8  0x0000000000421768 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:960
No locals.
#9  0x0000000000421c9a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:795
No locals.
#10 0x0000000000421d3e in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:773
No locals.
#11 0x0000000000421ec4 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:758
No locals.
#12 0x0000000000421ac0 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:947
        __mark = 1
        __r = {_M_nfa = @0x7fffffffdab0, _M_start = 8, _M_end1 = 8, _M_end2 = -1}
#13 0x0000000000421c9a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:795
No locals.
#14 0x0000000000421d3e in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:773
No locals.
#15 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 7, _M_end1 = 7, _M_end2 = -1}
#16 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 6, _M_end1 = 6, _M_end2 = -1}
#17 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 5, _M_end1 = 5, _M_end2 = -1}
#18 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 4, _M_end1 = 4, _M_end2 = -1}
#19 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 3, _M_end1 = 3, _M_end2 = -1}
#20 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 2, _M_end1 = 2, _M_end2 = -1}
#21 0x0000000000421d87 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=this@entry=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:776
        __re = {_M_nfa = @0x7fffffffdab0, _M_start = 1, _M_end1 = 1, _M_end2 = -1}
#22 0x0000000000421ec4 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7fffffffda60) at /usr/include/c++/4.8/bits/regex_compiler.h:758
No locals.
#23 0x0000000000422209 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler (this=0x7fffffffda60, __b=<optimised out>, __e=<optimised out>, __traits=..., 
    __flags=<optimised out>) at /usr/include/c++/4.8/bits/regex_compiler.h:729
        __r = {_M_nfa = @0x7fffffffdab0, _M_start = 0, _M_end1 = 0, _M_end2 = -1}
#24 0x00000000004226d1 in __compile<char const*, std::regex_traits<char> > (__f=16, __t=..., __e=@0x7fffffffda58: 0x424c5d "", 
    __b=@0x7fffffffda48: 0x424c10 "I: Bus=([0-9a-f]+) Vendor=([0-9a-f]+) Product=([0-9a-f]+) Version=([0-9a-f]+)") at /usr/include/c++/4.8/bits/regex_compiler.h:1105
No locals.
#25 std::basic_regex<char, std::regex_traits<char> >::basic_regex (this=0x62cb00 <(anonymous namespace)::REGEX_I>, 
    __p=0x424c10 "I: Bus=([0-9a-f]+) Vendor=([0-9a-f]+) Product=([0-9a-f]+) Version=([0-9a-f]+)", __f=<optimised out>) at /usr/include/c++/4.8/bits/regex.h:388
No locals.
#26 0x0000000000412596 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/username/codefunkeymonkey/include/evdevdevice.h:19
No locals.
#27 _GLOBAL__sub_I__ZN11EvdevDevice16availableDevicesEv () at /home/username/codefunkeymonkey/src/main.cpp:173
No locals.
#28 0x00000000004245dd in __libc_csu_init ()
No symbol table info available.
#29 0x00007ffff7318e55 in __libc_start_main (main=0x410720 <main(int, char**)>, argc=1, argv=0x7fffffffdca8, init=0x424590 <__libc_csu_init>, fini=<optimised out>, 
    rtld_fini=<optimised out>, stack_end=0x7fffffffdc98) at libc-start.c:246
        result = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 140737351947607, 140733193388033, 0, 140737349647704, 140737340535208, 0, 0}, mask_was_saved = 4269647}}, priv = {pad = {
              0x7ffff7df0515 <_dl_runtime_resolve+53>, 0x1c, 0x424590 <__libc_csu_init>, 0x7fffffffdca8}, data = {prev = 0x7ffff7df0515 <_dl_runtime_resolve+53>, cleanup = 0x1c, 
              canceltype = 4343184}}}
        not_first_call = <optimised out>
#30 0x0000000000412678 in _start ()
No symbol table info available.

**Comment by bzar** [comment]
Okay, I see the problem part. Will need to figure out why it fails for you though.

**Comment by pmprog** [comment]
Thanks, let me know if you need me to test anything or what not

**Comment by bzar** [comment]
Okay, found the reason. C++11 regex support was not ready until GCC 4.9. You have 4.8 there so it probably has missing features.

**Comment by pmprog** [comment]
Installing gcc4.9
